
import type { Translations } from './types';

// Empty arrays as we now use Firestore - No demo data
export const associations = [];
export const newsItems = [];
export const USERS = [];

export const saidaMunicipalities = [
  'سعيدة',
  'عين الحجر',
  'الحساسنة',
  'أولاد ابراهيم',
  'تيرسين',
  'يوب',
  'دوي ثابت',
  'عين السخونة',
  'أولاد خالد',
  'بالول',
  'عين السلطان',
  'المعمورة',
  'سيدي اعمر',
  'سيدي بوبكر',
  'هونت',
  'مولاي العربي'
];

export const TEXTS: Translations = {
  appName: { ar: 'وصال', fr: 'Wessal' },
  youthAssociations: { ar: 'جمعيات الشباب', fr: 'Associations de Jeunesse' },
  sportsAssociations: { ar: 'الجمعيات الرياضية', fr: 'Associations Sportives' },
  homeTitle: { ar: 'منصة وصال للجمعيات', fr: 'Plateforme Wessal' },
  homeSubtitle: { ar: 'همزة وصل بين الشباب و الجمعيات\nفي ولاية سعيدة', fr: 'Le lien entre la jeunesse et les associations\nde la wilaya de Saida' },
  searchByName: { ar: 'البحث باسم الجمعية...', fr: 'Rechercher par nom...' },
  filterByActivity: { ar: 'الفرز حسب النشاط', fr: 'Trier par activité' },
  filterByMunicipality: { ar: 'التصفية حسب البلدية', fr: 'Filtrer par commune' },
  all: { ar: 'الكل', fr: 'Tous' },
  noResults: { ar: 'لم يتم العثور على نتائج', fr: 'Aucun résultat trouvé' },
  associationDetails: { ar: 'تفاصيل الجمعية', fr: 'Détails de l\'association' },
  president: { ar: 'المسؤول / الرئيس', fr: 'Responsable / Président' },
  phone: { ar: 'الهاتف', fr: 'Téléphone' },
  email: { ar: 'البريد الإلكتروني', fr: 'Email' },
  address: { ar: 'العنوان', fr: 'Adresse' },
  activityType: { ar: 'نوع النشاط', fr: 'Type d\'activité' },
  workingHours: { ar: 'ساعات العمل', fr: 'Heures d\'ouverture' },
  foundedYear: { ar: 'سنة التأسيس', fr: 'Année de fondation' },
  members: { ar: 'عدد المنخرطين', fr: 'Nombre de membres' },
  socialMedia: { ar: 'مواقع التواصل', fr: 'Réseaux sociaux' },
  documents: { ar: 'وثائق للتحميل', fr: 'Documents à télécharger' },
  download: { ar: 'تحميل', fr: 'Télécharger' },
  addToFavorites: { ar: 'أضف إلى المفضلة', fr: 'Ajouter aux favoris' },
  removeFromFavorites: { ar: 'إزالة من المفضلة', fr: 'Retirer des favoris' },
  newsAndActivities: { ar: 'الأخبار والنشاطات', fr: 'Actualités et Activités' },
  favorites: { ar: 'المفضلة', fr: 'Favoris' },
  map: { ar: 'الخريطة', fr: 'Carte' },
  noFavorites: { ar: 'قائمة المفضلة فارغة. قم بإضافة جمعيات لكي تظهر هنا.', fr: 'La liste de favoris est vide. Ajoutez des associations pour les voir ici.' },
  associationsMap: { ar: 'خريطة مواقع الجمعيات', fr: 'Carte des emplacements des associations' },
  viewDetails: { ar: 'عرض التفاصيل', fr: 'Voir les détails' },
  footerText: { ar: '© 2025 وصال - جميع الحقوق محفوظة.', fr: '© 2025 Wessal - Tous droits réservés.' },
  home: { ar: 'الرئيسية', fr: 'Accueil' },
  login: { ar: 'تسجيل الدخول', fr: 'Connexion' },
  register: { ar: 'تسجيل جديد', fr: 'Inscription' },
  dashboard: { ar: 'لوحة التحكم', fr: 'Tableau de bord' },
  logout: { ar: 'تسجيل الخروج', fr: 'Déconnexion' },
  adminDashboard: { ar: 'لوحة التحكم الذكية', fr: 'Tableau de bord intelligent' },
  presidentDashboard: { ar: 'فضاء رئيس الجمعية', fr: 'Espace Président' },
  userDashboard: { ar: 'فضاء المستخدم', fr: 'Espace Utilisateur' },
  welcome: { ar: 'مرحبا', fr: 'Bienvenue' },
  manageAssociations: { ar: 'إدارة الجمعيات', fr: 'Gérer les associations' },
  addEditDeleteAssociations: { ar: 'إضافة، تعديل، وحذف الجمعيات.', fr: 'Ajouter, modifier et supprimer des associations.' },
  manageCategories: { ar: 'إدارة التصنيفات', fr: 'Gérer les catégories' },
  publishNews: { ar: 'نشر الأخبار', fr: 'Publier les actualités' },
  viewStats: { ar: 'الإحصائيات العامة', fr: 'Statistiques générales' },
  exportData: { ar: 'تصدير البيانات', fr: 'Exporter les données' },
  editMyAssociation: { ar: 'بيانات جمعيتي', fr: 'Données de mon association' },
  updateAssociationDetails: { ar: 'تحديث معلومات وتفاصيل الجمعية.', fr: 'Mettre à jour les informations de l\'association.' },
  manageMembers: { ar: 'إدارة المنخرطين', fr: 'Gérer les membres' },
  password: { ar: 'كلمة المرور', fr: 'Mot de passe' },
  fullName: { ar: 'الاسم الكامل', fr: 'Nom complet' },
  createAccount: { ar: 'إنشاء حساب', fr: 'Créer un compte' },
  iAmA: { ar: 'أنا', fr: 'Je suis un(e)' },
  regularUser: { ar: 'مستخدم عادي', fr: 'Utilisateur régulier' },
  associationPresident: { ar: 'رئيس جمعية', fr: 'Président d\'association' },
  alreadyHaveAccount: { ar: 'لديك حساب بالفعل؟', fr: 'Vous avez déjà un compte ?' },
  dontHaveAccount: { ar: 'ليس لديك حساب؟', fr: 'Pas de compte ?' },
  addAssociation: { ar: 'إضافة جمعية جديدة', fr: 'Ajouter une association' },
  editAssociation: { ar: 'تعديل الجمعية', fr: 'Modifier l\'association' },
  deleteAssociation: { ar: 'حذف الجمعية', fr: 'Supprimer l\'association' },
  confirmDelete: { ar: 'هل أنت متأكد من أنك تريد حذف هذه الجمعية؟', fr: 'Êtes-vous sûr de vouloir supprimer cette association ?' },
  save: { ar: 'حفظ', fr: 'Enregistrer' },
  cancel: { ar: 'إلغاء', fr: 'Annuler' },
  back: { ar: 'رجوع', fr: 'Retour' },
  nameAr: { ar: 'الاسم (بالعربية)', fr: 'Nom (Arabe)' },
  nameFr: { ar: 'الاسم (بالفرنسية)', fr: 'Nom (Français)' },
  category: { ar: 'الفئة', fr: 'Catégorie' },
  actions: { ar: 'إجراءات', fr: 'Actions' },
  edit: { ar: 'تعديل', fr: 'Modifier' },
  delete: { ar: 'حذف', fr: 'Supprimer' },
  logoUrl: { ar: 'رابط الشعار', fr: 'URL du logo' },
  latitude: { ar: 'خط العرض', fr: 'Latitude' },
  longitude: { ar: 'خط الطول', fr: 'Longitude' },
  requiredField: { ar: 'هذا الحقل مطلوب', fr: 'Ce champ est requis' },
  youth: { ar: 'شبابية', fr: 'Jeunesse' },
  sports: { ar: 'رياضية', fr: 'Sportive' },
  manageNews: { ar: 'إدارة الأخبار', fr: 'Gérer les actualités' },
  addNews: { ar: 'إضافة خبر جديد', fr: 'Ajouter une actualité' },
  editNews: { ar: 'تعديل الخبر', fr: 'Modifier l\'actualité' },
  deleteNews: { ar: 'حذف الخبر', fr: 'Supprimer l\'actualité' },
  confirmDeleteNews: { ar: 'هل أنت متأكد من أنك تريد حذف هذا الخبر؟', fr: 'Êtes-vous sûr de vouloir supprimer cette actualité ?' },
  titleAr: { ar: 'العنوان (بالعربية)', fr: 'Titre (Arabe)' },
  titleFr: { ar: 'العنوان (بالفرنسية)', fr: 'Titre (Français)' },
  summaryAr: { ar: 'الملخص (بالعربية)', fr: 'Résumé (Arabe)' },
  summaryFr: { ar: 'الملخص (بالفرنسية)', fr: 'Résumé (Français)' },
  date: { ar: 'التاريخ', fr: 'Date' },
  imageUrl: { ar: 'رابط الصورة', fr: 'URL de l\'image' },
  title: { ar: 'العنوان', fr: 'Titre' },
  users: { ar: 'المستخدمين', fr: 'Utilisateurs' },
  totalAssociations: { ar: 'إجمالي الجمعيات', fr: 'Total Associations' },
  totalMembers: { ar: 'إجمالي المنخرطين', fr: 'Total Membres' },
  systemHealth: { ar: 'حالة النظام', fr: 'État du système' },
  good: { ar: 'جيدة', fr: 'Bon' },
  manageUsers: { ar: 'إدارة المستخدمين', fr: 'Gérer les utilisateurs' },
  associationsMenu: { ar: 'الجمعيات', fr: 'Associations' },
  changePassword: { ar: 'تغيير كلمة المرور', fr: 'Changer le mot de passe' },
  currentPassword: { ar: 'كلمة المرور الحالية', fr: 'Mot de passe actuel' },
  newPassword: { ar: 'كلمة المرور الجديدة', fr: 'Nouveau mot de passe' },
  confirmPassword: { ar: 'تأكيد كلمة المرور', fr: 'Confirmer le mot de passe' },
  passwordMismatch: { ar: 'كلمات المرور غير متطابقة', fr: 'Les mots de passe ne correspondent pas' },
  passwordUpdated: { ar: 'تم تحديث كلمة المرور بنجاح', fr: 'Mot de passe mis à jour avec succès' },
  passwordsDoNotMatch: { ar: 'كلمات المرور لا تتطابق.', fr: 'Les mots de passe ne correspondent pas.' },
  passwordRequirements: { ar: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.', fr: 'Le mot de passe doit comporter au moins 6 caractères.' }
};
